### PR TITLE
Fix to run

### PR DESCRIPTION
**Pull request by eliot1019**

### CODE REVIEW

**Comment by eliot1019** [comment]
Some notes
-png supports 4 channels, jpg does not.
-The mat type we should use is CV_8UC4
-When getting a pixel value in mat, specify type as cv::Vec4b
-toARGB() commented out rn, check rayprocessor near bottom where outputbitmap pixel value is set
-i changed util::getNativeTextureBitmap for us cuz it seems like we aren’t using it
-Color in C# stores argb values as bytes, values from (0-255) whereas our ArgbColor stores values from 0.0-1.0 as a float
	• this is important because it changes the conversions from c# to c++. Check util.h’s add_color and get_brightness for an example

-you can check official colors here : https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.colors?redirectedfrom=MSDN&view=netframework-4.8

**Comment by eliot1019** [comment]
Also note on imread, opencv stores argb in the reverse order. 
vec4b[0] = blue ... vec4b[3] = alpha

**Comment by michaeltu1** [comment]
Resulting image is the same as the one Eliot gets, but stuff works for Windows now.

**Comment by eliot1019** [comment]
i accidentally force pushed to master as well but i reverted that already.

**Comment by eliot1019** [comment]
would be nice to get the relative/full path issue solved for the texture input images but looks like windows and unix have different implementations to get it.

**Review by michaeltu1 — APPROVED** [review]

**Pull request merged**
