### PR TITLE
Add Windows Compatibility and README.md

### PR DESCRIPTION
**Pull request by michaeltu1**

### CODE REVIEW

**Comment by eliot1019** [comment]
I added `if windows` checks around `#include <corecrt_math_defines.h>` to get the mac build to compile.
could you see if this affects your build?
Also, to fully remove our dependency on CGL, we'll need to delete the folder and all the `#include CGL` references.

**Comment by michaeltu1** [comment]
The `if windows` check work, having some difficulty with replacing the CGL references. Worst case the CGL library can be found [here](https://github.com/cal-cs184/p1-rasterizer/tree/master/CGL).

**Comment by michaeltu1** [comment]
Removed the `vector.*` and `matrix4x4.*` files. We should remove dependencies in a separate pr.

**Comment by michaeltu1** [comment]
Not sure how this project works on mac or how to install OpenCV for mac. Someone else should update the readme with instructions. I added a sample image, but it won't properly display until the `samples` folder with the image are merged into master.

**Pull request merged**
